"""initial schema

Revision ID: 1eb63329a9dc
Revises: 
Create Date: 2026-08-27 08:50:28.940334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eb63329a9dc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pets',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('age', sa.Integer(), server_default='-1', nullable=False),
    sa.Column('days_stay', sa.Integer(), server_default='-1', nullable=False),
    sa.Column('amount_due', sa.Float(), server_default='-1.0', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    op.execute(
    """
    ALTER TABLE users ENABLE ROW LEVEL SECURITY;
    """ 
    )

    op.execute(
        """
        CREATE POLICY users_policy on users
            FOR ALL 
            USING (id = NULLIF(current_setting('app.user_id', true), '')::uuid)
            WITH CHECK (id = NULLIF(current_setting('app.user_id', true), '')::uuid);
        """
    )

    op.execute(
        """
        ALTER TABLE pets ENABLE ROW LEVEL SECURITY;
        """
    )

    op.execute(
        """
        CREATE POLICY users_pets_policy on pets
            FOR ALL
            USING (user_id = NULLIF(current_setting('app.user_id', true), '')::uuid)
            WITH CHECK (user_id = NULLIF(current_setting('app.user_id', true), '')::uuid);
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pets')
    op.drop_table('users')
    # ### end Alembic commands ###
