"""new tables and cols

Revision ID: d2073caa02f4
Revises: 1eb63329a9dc
Create Date: 2026-09-14 17:31:22.728244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2073caa02f4'
down_revision: Union[str, Sequence[str], None] = '1eb63329a9dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shelters',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('size', sa.Integer(), server_default='-1', nullable=False),
    sa.Column('external_link', sa.String(), nullable=False),
    sa.Column('geo_location1', sa.String(length=2), nullable=False),
    sa.Column('geo_location2', sa.String(length=2), nullable=False),
    sa.Column('longitude', sa.Float(), server_default='-1.0', nullable=False),
    sa.Column('latitude', sa.Float(), server_default='-1.0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applications',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('pet_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('ACCEPTED', 'REJECTED', 'PENDING', name='applicationstatus'), nullable=False),
    sa.Column('user_notes', sa.String(length=500), nullable=False),
    sa.Column('shelter_notes', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('pet_id', sa.Uuid(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('pets', sa.Column('shelter_id', sa.Uuid(), nullable=True))
    op.add_column('pets', sa.Column('breed', sa.String(length=50), nullable=False))
    op.add_column('pets', sa.Column('days_in', sa.Integer(), server_default='-1', nullable=False))
    op.add_column('pets', sa.Column('adoption_price', sa.Float(), server_default='-1.0', nullable=False))
    op.alter_column('pets', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    animal_type = sa.Enum(
        'DEFAULT',
        'DOG',
        'CAT',
        'OTHER',
        name='animaltype'
    )
    animal_type.create(op.get_bind(), checkfirst=True)
    op.alter_column('pets', 'type',
                existing_type=sa.VARCHAR(length=20),
                type_=animal_type,
                existing_nullable=False,
                postgresql_using='"type"::animaltype')
    op.drop_constraint(op.f('pets_user_id_fkey'), 'pets', type_='foreignkey')
    op.create_foreign_key(None, 'pets', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'pets', 'shelters', ['shelter_id'], ['id'], ondelete='SET NULL')
    op.drop_column('pets', 'amount_due')
    op.drop_column('pets', 'days_stay')
    op.add_column('users', sa.Column('shelter_id', sa.Uuid(), nullable=True))
    employee_role = sa.Enum(
        'DEFAULT', 
        'OWNER', 
        'ADMIN', 
        'EMPLOYEE', 
        'OTHER',
        name='employeerole'
    )
    employee_role.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('role', employee_role, nullable=False, server_default='DEFAULT'))
    op.create_foreign_key(None, 'users', 'shelters', ['shelter_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role')
    op.drop_column('users', 'shelter_id')
    op.add_column('pets', sa.Column('days_stay', sa.INTEGER(), server_default=sa.text("'-1'::integer"), autoincrement=False, nullable=False))
    op.add_column('pets', sa.Column('amount_due', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'-1'::double precision"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pets', type_='foreignkey')
    op.drop_constraint(None, 'pets', type_='foreignkey')
    op.create_foreign_key(op.f('pets_user_id_fkey'), 'pets', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('pets', 'type',
               existing_type=sa.Enum('DEFAULT', 'DOG', 'CAT', 'OTHER', name='animaltype'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('pets', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('pets', 'adoption_price')
    op.drop_column('pets', 'days_in')
    op.drop_column('pets', 'breed')
    op.drop_column('pets', 'shelter_id')
    op.drop_table('appointments')
    op.drop_table('applications')
    op.drop_table('shelters')
    # ### end Alembic commands ###
